using EgyptExploring.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EgyptExploring.Configurations
{
    public class DestinationConfig : IEntityTypeConfiguration<Destination>
    {
        public void Configure(EntityTypeBuilder<Destination> builder)
        {
            builder.HasData(LoadDestinations());
        }
        private List<Destination> LoadDestinations()
        {
            return new List<Destination>
            {
// ---------------------- Cairo ----------------------
new Destination { DestinationId = 1, DestinationName = "Egyptian Museum", CityId = 1, Description = "Home to the world's largest collection of ancient Egyptian artifacts, including the treasures of Tutankhamun and over 120,000 items spanning 5,000 years of Egyptian history.", ImageUrl = "~/images/Cairo/EgyptionMuseum.jpg" },
new Destination { DestinationId = 2, DestinationName = "Cairo Tower", CityId = 1, Description = "A 187-meter tall tower offering panoramic views of Cairo, featuring a revolving restaurant at the top and designed to resemble a lotus flower.", ImageUrl = "~/images/Cairo/CairoTower.jpg" },
new Destination { DestinationId = 3, DestinationName = "Al-Azhar Mosque", CityId = 1, Description = "One of Cairo's oldest mosques and a center of Islamic learning for over a millennium, featuring stunning Fatimid architecture and beautiful courtyards.", ImageUrl = "~/images/Cairo/Alazhar.jpg" },
new Destination { DestinationId = 4, DestinationName = "Khan El Khalili", CityId = 1, Description = "A historic bazaar dating back to 1382, filled with traditional shops, spice vendors, jewelry stores, and cafes in the heart of Islamic Cairo.", ImageUrl = "~/images/Cairo/KhanKhalili.jpg" },
new Destination { DestinationId = 5, DestinationName = "Citadel of Saladin", CityId = 1, Description = "A medieval Islamic fortification built in the 12th century, housing the magnificent Muhammad Ali Mosque and offering sweeping views of Cairo.", ImageUrl = "~/images/Cairo/CitiadelofSalah.jpg" },
new Destination { DestinationId = 6, DestinationName = "Ibn Tulun Mosque", CityId = 1, Description = "One of the oldest and largest mosques in Cairo, built in 879 AD, featuring a unique spiral minaret and spacious courtyard with stunning Islamic architecture.", ImageUrl = "~/images/Cairo/CairoIbnTulunMoschee.jpg" },
new Destination { DestinationId = 7, DestinationName = "Coptic Museum", CityId = 1, Description = "A museum showcasing the rich history of Coptic Christianity in Egypt with manuscripts, textiles, icons, and artifacts from the Roman era to Islamic period.", ImageUrl = "~/images/Cairo/CopticMuseum.jpg" },
new Destination { DestinationId = 8, DestinationName = "Al-Muizz Street", CityId = 1, Description = "A historic street in Islamic Cairo lined with magnificent mosques, madrasas, and medieval architecture, recognized as one of the greatest concentrations of Islamic monuments in the world.", ImageUrl = "~/images/Cairo/al muizz.jpg" },

// ---------------------- Giza ----------------------
new Destination { DestinationId = 9, DestinationName = "Giza Pyramids", CityId = 2, Description = "The last surviving wonder of the ancient world, featuring the Great Pyramid of Khufu, Pyramid of Khafre, and Pyramid of Menkaure, built over 4,500 years ago.", ImageUrl = "~/images/Giza/Giza Pyramids.jpg" },
new Destination { DestinationId = 10, DestinationName = "Great Sphinx", CityId = 2, Description = "A colossal limestone statue with a lion's body and human head, standing guard at the Giza pyramid complex for millennia.", ImageUrl = "~/images/Giza/Great Sphinx.jpg" },
new Destination { DestinationId = 11, DestinationName = "Saqqara Step Pyramid", CityId = 2, Description = "The oldest complete stone building complex known in history, built for Pharaoh Djoser around 2630 BC by architect Imhotep.", ImageUrl = "~/images/Giza/Saqqara Step Pyramid.jpg" },
new Destination { DestinationId = 12, DestinationName = "Memphis Open-Air Museum", CityId = 2, Description = "An outdoor museum showcasing artifacts from ancient Memphis, Egypt's first capital, including a massive limestone statue of Ramses II.", ImageUrl = "~/images/Giza/Memphis Open-Air Museum.jpg" },
new Destination { DestinationId = 13, DestinationName = "Dahshur Pyramids", CityId = 2, Description = "Home to the Bent Pyramid and Red Pyramid, offering a quieter alternative to Giza with well-preserved structures and fewer crowds.", ImageUrl = "~/images/Giza/Dahshur Pyramids.jpg" },
new Destination { DestinationId = 14, DestinationName = "Solar Boat Museum", CityId = 2, Description = "Houses a reconstructed ancient Egyptian boat that was buried at the foot of the Great Pyramid, intended to carry Khufu through the afterlife.", ImageUrl = "~/images/Giza/Khufuship.jpg" },

// ---------------------- Alexandria ----------------------
new Destination { DestinationId = 15, DestinationName = "Bibliotheca Alexandrina", CityId = 3, Description = "A stunning modern library and cultural center built to commemorate the ancient Library of Alexandria, featuring millions of books and multiple museums.", ImageUrl = "~/images/Alex/Bibliotecha.jpg" },
new Destination { DestinationId = 16, DestinationName = "Qaitbay Citadel", CityId = 3, Description = "A 15th-century defensive fortress built on the exact site of the ancient Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World.", ImageUrl = "~/images/Alex/CitadelofQaitbay.jpg" },
new Destination { DestinationId = 17, DestinationName = "Montaza Palace Gardens", CityId = 3, Description = "Sprawling royal gardens along the Mediterranean coast featuring beautiful landscapes, beaches, and the former summer residence of Egyptian royalty.", ImageUrl = "~/images/Alex/MontazaPalacegarden.jpg" },
new Destination { DestinationId = 18, DestinationName = "Alexandria National Museum", CityId = 3, Description = "A museum housed in an Italian-style palace, displaying artifacts from Alexandria's Pharaonic, Roman, Coptic, and Islamic periods.", ImageUrl = "~/images/Alex/AlexandriaNationalMuseum.jpg" },
new Destination { DestinationId = 19, DestinationName = "Pompey's Pillar", CityId = 3, Description = "A massive 27-meter red granite column erected in 297 AD, the largest ancient monument in Alexandria and a remnant of the Serapeum temple.", ImageUrl = "~/images/Alex/PompeysPillar.jpg" },
new Destination { DestinationId = 20, DestinationName = "Stanley Bridge", CityId = 3, Description = "A modern landmark bridge along Alexandria's Corniche, beautifully illuminated at night and offering spectacular Mediterranean Sea views.", ImageUrl = "~/images/Alex/StanleybridgeinAlexandria.jpg" },
new Destination { DestinationId = 21, DestinationName = "Catacombs of Kom el Shoqafa", CityId = 3, Description = "A historical archaeological site featuring a complex of tombs blending Roman, Greek, and Egyptian cultural elements, dating from the 2nd century AD.", ImageUrl = "~/images/Alex/CornicheAlexandria.jpg" },
new Destination { DestinationId = 22, DestinationName = "Roman Amphitheatre", CityId = 3, Description = "A well-preserved Roman theater discovered in 1960, featuring marble seating, mosaic floors, and remains of ancient baths and villas.", ImageUrl = "~/images/Alex/CornicheAlexandria.jpg" },

// ---------------------- Luxor ----------------------
new Destination { DestinationId = 23, DestinationName = "Karnak Temple", CityId = 4, Description = "The largest ancient religious complex ever built, covering over 200 acres with massive columns, obelisks, and the famous Great Hypostyle Hall.", ImageUrl = "~/images/Luxuor/Karnak.jpg" },
new Destination { DestinationId = 24, DestinationName = "Luxor Temple", CityId = 4, Description = "A magnificent temple complex built around 1400 BC, beautifully illuminated at night and connected to Karnak by the ancient Avenue of Sphinxes.", ImageUrl = "~/images/Luxuor/Louxordromospylône.jpeg" },
new Destination { DestinationId = 25, DestinationName = "Valley of the Kings", CityId = 4, Description = "An ancient necropolis containing 63 tombs of pharaohs including Tutankhamun, adorned with intricate hieroglyphics and colorful wall paintings.", ImageUrl = "~/images/Luxuor/LuxorTalderKönige.jpg" },
new Destination { DestinationId = 26, DestinationName = "Hatshepsut Temple", CityId = 4, Description = "A stunning mortuary temple built for Egypt's most successful female pharaoh, featuring three terraced levels carved into limestone cliffs.", ImageUrl = "~/images/Luxuor/TemploHatshepsut.jpg" },
new Destination { DestinationId = 27, DestinationName = "Colossi of Memnon", CityId = 4, Description = "Two massive stone statues of Pharaoh Amenhotep III, standing 18 meters tall and guarding the entrance to his mortuary temple for 3,400 years.", ImageUrl = "~/images/Luxuor/Hotairballooning.jpg" },
new Destination { DestinationId = 28, DestinationName = "Luxor Museum", CityId = 4, Description = "A world-class museum displaying carefully curated artifacts from Thebes and the surrounding area, including royal mummies and exquisite statuary.", ImageUrl = "~/images/Luxuor/LuxorMuseum.jpg" },
new Destination { DestinationId = 29, DestinationName = "Valley of the Queens", CityId = 4, Description = "An ancient burial site for queens and royal children, featuring beautifully decorated tombs including the famous tomb of Queen Nefertari.", ImageUrl = "~/images/Luxuor/NileinLuxor.jpg" },
new Destination { DestinationId = 30, DestinationName = "Medinet Habu", CityId = 4, Description = "The mortuary temple of Ramses III, one of the best-preserved temples in Egypt with massive walls covered in detailed battle scenes and hieroglyphics.", ImageUrl = "~/images/Luxuor/NileinLuxor.jpg" },

// ---------------------- Aswan ----------------------
new Destination { DestinationId = 31, DestinationName = "Philae Temple", CityId = 5, Description = "An enchanting temple complex dedicated to the goddess Isis, relocated to Agilkia Island and beautifully preserved with stunning hieroglyphics and columns.", ImageUrl = "~/images/Aswan/PhilaeTemple.jpg" },
new Destination { DestinationId = 32, DestinationName = "Aswan High Dam", CityId = 5, Description = "A massive engineering marvel completed in 1970, controlling Nile flooding and creating Lake Nasser, one of the world's largest artificial lakes.", ImageUrl = "~/images/Aswan/AswanHighDamNorth.jpg" },
new Destination { DestinationId = 33, DestinationName = "Nubian Museum", CityId = 5, Description = "An award-winning museum showcasing the rich history and culture of Nubia, with artifacts spanning from prehistoric times to the present day.", ImageUrl = "~/images/Aswan/NubianMuseum.jpg" },
new Destination { DestinationId = 34, DestinationName = "Unfinished Obelisk", CityId = 5, Description = "A massive obelisk still attached to its bedrock, offering unique insights into ancient Egyptian stone-working techniques and quarrying methods.", ImageUrl = "~/images/Aswan/UnfinishedObeliskinAswan.jpg" },
new Destination { DestinationId = 35, DestinationName = "Elephantine Island", CityId = 5, Description = "An ancient island settlement containing Nubian villages, archaeological ruins, and the Aswan Museum, set in the middle of the Nile River.", ImageUrl = "~/images/Aswan/Elephantine.jpeg" },
new Destination { DestinationId = 36, DestinationName = "Abu Simbel Temples", CityId = 5, Description = "Two massive rock-cut temples built by Ramses II, featuring four colossal statues at the entrance and relocated to save them from Lake Nasser.", ImageUrl = "~/images/Aswan/TemploRamsésIIAbu_Simbel.jpg" },
new Destination { DestinationId = 37, DestinationName = "Nubian Village", CityId = 5, Description = "Colorful traditional villages where Nubian culture thrives, offering authentic experiences with local crafts, music, cuisine, and warm hospitality.", ImageUrl = "~/images/Aswan/NubianVillage.jpg" },

// ---------------------- Sharm El Sheikh ----------------------
new Destination { DestinationId = 38, DestinationName = "Ras Mohammed National Park", CityId = 6, Description = "Egypt's first national park featuring pristine coral reefs, diverse marine life, and stunning desert landscapes at the southern tip of the Sinai Peninsula.", ImageUrl = "~/images/SharmElshiekh/RasMuhammad.jpg" },
new Destination { DestinationId = 39, DestinationName = "Naama Bay", CityId = 6, Description = "A vibrant beachfront promenade lined with restaurants, shops, and hotels, offering crystal-clear waters perfect for swimming and snorkeling.", ImageUrl = "~/images/SharmElshiekh/NaamaBay.jpg" },
new Destination { DestinationId = 40, DestinationName = "SOHO Square", CityId = 6, Description = "A modern entertainment complex featuring restaurants, ice skating, fountains, open-air cinema, and nightly cultural shows in a beautifully designed plaza.", ImageUrl = "~/images/SharmElshiekh/SOHOSquare.jpg" },
new Destination { DestinationId = 41, DestinationName = "Old Market", CityId = 6, Description = "A traditional Egyptian bazaar offering authentic shopping experiences with spices, textiles, souvenirs, and local handicrafts at bargain prices.", ImageUrl = "~/images/SharmElshiekh/SharmElSheikhOldMarket.jpg" },
new Destination { DestinationId = 42, DestinationName = "Shark's Bay", CityId = 6, Description = "A tranquil beach area known for its excellent diving and snorkeling spots, with easy access to beautiful coral reefs and marine life.", ImageUrl = "~/images/SharmElshiekh/SharksBay.jpeg" },
new Destination { DestinationId = 43, DestinationName = "Tiran Island", CityId = 6, Description = "A breathtaking island famous for its crystal-clear waters, rich coral reefs, and vibrant marine life—one of Sharm El Sheikh’s top snorkeling and diving destinations.", ImageUrl = "~/images/SharmElshiekh/TiranIsland.jpg" },

// ---------------------- Hurghada ----------------------
new Destination { DestinationId = 44, DestinationName = "Giftun Island", CityId = 7, Description = "A protected marine reserve with pristine white sandy beaches, crystal-clear turquoise waters, and some of the Red Sea's best snorkeling spots.", ImageUrl = "~/images/Hurghada/Giftunisland.jpg" },
new Destination { DestinationId = 45, DestinationName = "Hurghada Marina", CityId = 7, Description = "A modern waterfront development featuring luxury yachts, upscale restaurants, boutique shops, and vibrant nightlife along scenic boardwalks.", ImageUrl = "~/images/Hurghada/HurghadaMarina.jpg" },
new Destination { DestinationId = 46, DestinationName = "El Dahar Old Town", CityId = 7, Description = "The historic heart of Hurghada with traditional Egyptian markets, authentic local eateries, and a glimpse into the city's fishing village origins.", ImageUrl = "~/images/Hurghada/SahlHasheesh.jpg" },
new Destination { DestinationId = 47, DestinationName = "Sand City Hurghada", CityId = 7, Description = "An impressive open-air museum featuring over 40 intricate sand sculptures depicting historical figures, mythology, and Egyptian landmarks.", ImageUrl = "~/images/Hurghada/ElGouna.jpg" },
new Destination { DestinationId = 48, DestinationName = "Hurghada Grand Aquarium", CityId = 7, Description = "A state-of-the-art aquarium showcasing Red Sea marine life, rainforest exhibits, and interactive experiences with diverse aquatic species.", ImageUrl = "~/images/Hurghada/Grand Aquarium.jpg" },
new Destination { DestinationId = 49, DestinationName = "Makadi Water World", CityId = 7, Description = "One of Africa's largest water parks featuring thrilling slides, wave pools, lazy rivers, and family-friendly attractions spread across 50 attractions.", ImageUrl = "~/images/Hurghada/MakadiBay.jpg" },

// ---------------------- Fayoum ----------------------
new Destination { DestinationId = 50, DestinationName = "Wadi El Rayan Waterfalls", CityId = 8, Description = "Egypt's only natural waterfalls, created when two artificial lakes were connected, surrounded by stunning desert landscapes and diverse wildlife.", ImageUrl = "~/images/Fayoum/WaterfallsofWadiElRayan.jpg" },
new Destination { DestinationId = 51, DestinationName = "Wadi El Hitan", CityId = 8, Description = "A UNESCO World Heritage Site known as Valley of the Whales, containing fossils of ancient whales that demonstrate their evolution from land mammals.", ImageUrl = "~/images/Fayoum/DimihElseba.jpg" },
new Destination { DestinationId = 52, DestinationName = "Qarun Lake", CityId = 8, Description = "Egypt's third-largest lake and oldest natural lake, offering birdwatching opportunities, fishing, and scenic desert views dating back 70 million years.", ImageUrl = "~/images/Fayoum/QarunLake.jpg" },
new Destination { DestinationId = 53, DestinationName = "Tunis Village", CityId = 8, Description = "A charming artistic village known for pottery workshops, galleries, eco-lodges, and stunning views of Lake Qarun and surrounding landscapes.", ImageUrl = "~/images/Fayoum/TunisVillage.jpg" },
new Destination { DestinationId = 54, DestinationName = "Kom Oshim Museum", CityId = 8, Description = "An archaeological museum displaying artifacts from ancient Fayoum, including Greco-Roman period findings and the famous Fayoum portraits.", ImageUrl = "~/images/Fayoum/HawaraPyramid.jpeg" },
new Destination { DestinationId = 55, DestinationName = "Madinet Madi Temple", CityId = 8, Description = "A well-preserved Middle Kingdom temple dedicated to the serpent goddess Renenutet, featuring intact stone structures and ancient reliefs.", ImageUrl = "~/images/Fayoum/MagicLake.jpg" },

// ---------------------- Sinai ----------------------
new Destination { DestinationId = 56, DestinationName = "Mount Sinai", CityId = 9, Description = "A sacred mountain where Moses is believed to have received the Ten Commandments, offering spectacular sunrise views and spiritual significance to three major religions.", ImageUrl = "~/images/Sinai/sinaiMount.jpeg" },
new Destination { DestinationId = 57, DestinationName = "Saint Catherine's Monastery", CityId = 9, Description = "The world's oldest continuously functioning Christian monastery, built in the 6th century and housing priceless icons, manuscripts, and the alleged burning bush.", ImageUrl = "~/images/Sinai/Katharinenkloster.jpg" },
new Destination { DestinationId = 58, DestinationName = "Colored Canyon", CityId = 9, Description = "A stunning natural wonder featuring narrow passages between towering walls of multicolored sandstone in shades of red, yellow, purple, and gold.", ImageUrl = "~/images/Sinai/AbuGalumProtectorate.jpg" },
new Destination { DestinationId = 59, DestinationName = "Blue Hole Dahab", CityId = 9, Description = "A world-famous diving site consisting of a 130-meter deep submarine sinkhole with crystal-clear waters and vibrant coral formations.", ImageUrl = "~/images/Sinai/theBlueHole.jpg" },
new Destination { DestinationId = 60, DestinationName = "Abu Galum Reserve", CityId = 9, Description = "A protected area of pristine beaches, coral reefs, and rugged mountains, accessible only by camel or foot, offering untouched natural beauty.", ImageUrl = "~/images/Sinai/AbuGalumProtectorate.jpg" },
new Destination { DestinationId = 61, DestinationName = "Nuweiba Castle", CityId = 9, Description = "A historic Ottoman fortress overlooking the Gulf of Aqaba, offering insights into the region's strategic military history and coastal defense systems.", ImageUrl = "~/images/Sinai/Nuweiba.jpg" },

// ---------------------- Marsa Alam ----------------------
new Destination { DestinationId = 62, DestinationName = "Abu Dabbab Bay", CityId = 10, Description = "A sheltered bay famous for swimming with sea turtles and dugongs in crystal-clear shallow waters, ideal for snorkeling and underwater photography.", ImageUrl = "~/images/MarsaAlam/Abu_Dabbab.jpg" },
new Destination { DestinationId = 63, DestinationName = "Sataya Dolphin Reef", CityId = 10, Description = "A horseshoe-shaped reef known for resident pods of spinner dolphins, offering unforgettable opportunities to swim alongside these playful marine mammals.", ImageUrl = "~/images/MarsaAlam/Sataya Dolphin Reef.jpg" },
new Destination { DestinationId = 64, DestinationName = "El Qulan Mangrove Forest", CityId = 10, Description = "One of the northernmost mangrove forests on Earth, featuring unique ecosystems with diverse birdlife and marine species in protected coastal waters.", ImageUrl = "~/images/MarsaAlam/Qulan.jpg" },
new Destination { DestinationId = 65, DestinationName = "Wadi El Gemal National Park", CityId = 10, Description = "A vast protected area encompassing desert mountains, pristine beaches, coral reefs, and Bedouin heritage sites along 60 kilometers of coastline.", ImageUrl = "~/images/MarsaAlam/Wadi_el_Gemal.jpg" },
new Destination { DestinationId = 66, DestinationName = "Port Ghalib Marina", CityId = 10, Description = "A luxurious resort marina offering waterfront dining, shopping, yacht charters, and diving excursions in an elegant Mediterranean-style setting.", ImageUrl = "~/images/MarsaAlam/PortGhalibMarina.jpg" },
new Destination { DestinationId = 67, DestinationName = "Samadai Dolphin House", CityId = 10, Description = "A protected horseshoe-shaped reef sanctuary where spinner dolphins rest during the day, offering regulated swimming encounters with these graceful creatures.", ImageUrl = "~/images/MarsaAlam/samadi.jpg" },

// ---------------------- Matrouh ----------------------
new Destination { DestinationId = 68, DestinationName = "Cleopatra Beach", CityId = 11, Description = "A stunning beach surrounded by natural rock formations creating a protected swimming cove, where Cleopatra allegedly bathed during her visits.", ImageUrl = "~/images/Matrouh/Cleopatra.jpg" },
new Destination { DestinationId = 69, DestinationName = "Marsa Matrouh Corniche", CityId = 11, Description = "A scenic coastal promenade stretching along pristine Mediterranean beaches with turquoise waters, cafes, and stunning sunset views.", ImageUrl = "~/images/Matrouh/Marsa Matrouh Corniche.jpg" },
new Destination { DestinationId = 70, DestinationName = "Al Aghla Beach", CityId = 11, Description = "A beautiful white sand beach with crystal-clear shallow waters, perfect for families and swimmers seeking a peaceful Mediterranean coastal experience.", ImageUrl = "~/images/Matrouh/Algbla beach.jpg" },
new Destination { DestinationId = 71, DestinationName = "Matrouh War Museum", CityId = 11, Description = "A museum documenting the North African Campaign of World War II, featuring military artifacts, weapons, and exhibits about the desert battles.", ImageUrl = "~/images/Matrouh/warmuseum.webp" },
new Destination { DestinationId = 72, DestinationName = "Rommel Museum", CityId = 11, Description = "Located in a cave used as Field Marshal Rommel's headquarters during WWII, displaying military equipment and information about the Desert Fox's campaigns.", ImageUrl = "~/images/Matrouh/Rommel.jpg" },
            };
        }
    }
}
