// <auto-generated />
using System;
using EgyptExploring.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EgyptExploring.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EgyptExploring.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EgyptExploring.Models.Booking", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPersons")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TripId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("EgyptExploring.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Citys", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Cairo",
                            Image = "~/images/Cairo/CairoTower.jpg"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Giza",
                            Image = "~/images/pyramid-giza.jpg"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Alexandria",
                            Image = "~/images/library-alexandria-anniversary-closure.jpg"
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Luxor",
                            Image = "~/images/low-angle-shot-main-entrance-temple-horus-edfu-egypt.jpg"
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Aswan",
                            Image = "~/images/shot-numerous-boats-berthed-by-pier-straight-lines-sunset.jpg"
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Sharm El Sheikh",
                            Image = "~/images/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky-white-cloud.jpg"
                        },
                        new
                        {
                            CityId = 7,
                            CityName = "Hurghada",
                            Image = "~/images/scenic-view-private-sandy-beach-with-sun-beds-parasokamy-sea-mountains-resort.jpg"
                        },
                        new
                        {
                            CityId = 8,
                            CityName = "Fayoum",
                            Image = "~/images/Fayoum/WaterfallsofWadiElRayan.jpg"
                        },
                        new
                        {
                            CityId = 9,
                            CityName = "Sinai",
                            Image = "~/images/raimond-klavins-zfeY8HkSAOE-unsplash.jpg"
                        },
                        new
                        {
                            CityId = 10,
                            CityName = "Marsa Alam",
                            Image = "~/images/caption.jpg"
                        },
                        new
                        {
                            CityId = 11,
                            CityName = "Matrouh",
                            Image = "~/images/date-palms-oasis-sahara-desert.jpg"
                        });
                });

            modelBuilder.Entity("EgyptExploring.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinationId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinationId");

                    b.HasIndex("CityId");

                    b.ToTable("Destinations", (string)null);

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            CityId = 1,
                            Description = "Home to the world's largest collection of ancient Egyptian artifacts, including the treasures of Tutankhamun and over 120,000 items spanning 5,000 years of Egyptian history.",
                            DestinationName = "Egyptian Museum",
                            ImageUrl = "~/images/Cairo/EgyptionMuseum.jpg"
                        },
                        new
                        {
                            DestinationId = 2,
                            CityId = 1,
                            Description = "A 187-meter tall tower offering panoramic views of Cairo, featuring a revolving restaurant at the top and designed to resemble a lotus flower.",
                            DestinationName = "Cairo Tower",
                            ImageUrl = "~/images/Cairo/CairoTower.jpg"
                        },
                        new
                        {
                            DestinationId = 3,
                            CityId = 1,
                            Description = "One of Cairo's oldest mosques and a center of Islamic learning for over a millennium, featuring stunning Fatimid architecture and beautiful courtyards.",
                            DestinationName = "Al-Azhar Mosque",
                            ImageUrl = "~/images/Cairo/Alazhar.jpg"
                        },
                        new
                        {
                            DestinationId = 4,
                            CityId = 1,
                            Description = "A historic bazaar dating back to 1382, filled with traditional shops, spice vendors, jewelry stores, and cafes in the heart of Islamic Cairo.",
                            DestinationName = "Khan El Khalili",
                            ImageUrl = "~/images/Cairo/KhanKhalili.jpg"
                        },
                        new
                        {
                            DestinationId = 5,
                            CityId = 1,
                            Description = "A medieval Islamic fortification built in the 12th century, housing the magnificent Muhammad Ali Mosque and offering sweeping views of Cairo.",
                            DestinationName = "Citadel of Saladin",
                            ImageUrl = "~/images/Cairo/CitiadelofSalah.jpg"
                        },
                        new
                        {
                            DestinationId = 6,
                            CityId = 1,
                            Description = "One of the oldest and largest mosques in Cairo, built in 879 AD, featuring a unique spiral minaret and spacious courtyard with stunning Islamic architecture.",
                            DestinationName = "Ibn Tulun Mosque",
                            ImageUrl = "~/images/Cairo/CairoIbnTulunMoschee.jpg"
                        },
                        new
                        {
                            DestinationId = 7,
                            CityId = 1,
                            Description = "A museum showcasing the rich history of Coptic Christianity in Egypt with manuscripts, textiles, icons, and artifacts from the Roman era to Islamic period.",
                            DestinationName = "Coptic Museum",
                            ImageUrl = "~/images/Cairo/CopticMuseum.jpg"
                        },
                        new
                        {
                            DestinationId = 8,
                            CityId = 1,
                            Description = "A historic street in Islamic Cairo lined with magnificent mosques, madrasas, and medieval architecture, recognized as one of the greatest concentrations of Islamic monuments in the world.",
                            DestinationName = "Al-Muizz Street",
                            ImageUrl = "~/images/Cairo/al muizz.jpg"
                        },
                        new
                        {
                            DestinationId = 9,
                            CityId = 2,
                            Description = "The last surviving wonder of the ancient world, featuring the Great Pyramid of Khufu, Pyramid of Khafre, and Pyramid of Menkaure, built over 4,500 years ago.",
                            DestinationName = "Giza Pyramids",
                            ImageUrl = "~/images/Giza/Giza Pyramids.jpg"
                        },
                        new
                        {
                            DestinationId = 10,
                            CityId = 2,
                            Description = "A colossal limestone statue with a lion's body and human head, standing guard at the Giza pyramid complex for millennia.",
                            DestinationName = "Great Sphinx",
                            ImageUrl = "~/images/Giza/Great Sphinx.jpg"
                        },
                        new
                        {
                            DestinationId = 11,
                            CityId = 2,
                            Description = "The oldest complete stone building complex known in history, built for Pharaoh Djoser around 2630 BC by architect Imhotep.",
                            DestinationName = "Saqqara Step Pyramid",
                            ImageUrl = "~/images/Giza/Saqqara Step Pyramid.jpg"
                        },
                        new
                        {
                            DestinationId = 12,
                            CityId = 2,
                            Description = "An outdoor museum showcasing artifacts from ancient Memphis, Egypt's first capital, including a massive limestone statue of Ramses II.",
                            DestinationName = "Memphis Open-Air Museum",
                            ImageUrl = "~/images/Giza/Memphis Open-Air Museum.jpg"
                        },
                        new
                        {
                            DestinationId = 13,
                            CityId = 2,
                            Description = "Home to the Bent Pyramid and Red Pyramid, offering a quieter alternative to Giza with well-preserved structures and fewer crowds.",
                            DestinationName = "Dahshur Pyramids",
                            ImageUrl = "~/images/Giza/Dahshur Pyramids.jpg"
                        },
                        new
                        {
                            DestinationId = 14,
                            CityId = 2,
                            Description = "Houses a reconstructed ancient Egyptian boat that was buried at the foot of the Great Pyramid, intended to carry Khufu through the afterlife.",
                            DestinationName = "Solar Boat Museum",
                            ImageUrl = "~/images/Giza/Khufuship.jpg"
                        },
                        new
                        {
                            DestinationId = 15,
                            CityId = 3,
                            Description = "A stunning modern library and cultural center built to commemorate the ancient Library of Alexandria, featuring millions of books and multiple museums.",
                            DestinationName = "Bibliotheca Alexandrina",
                            ImageUrl = "~/images/Alex/Bibliotecha.jpg"
                        },
                        new
                        {
                            DestinationId = 16,
                            CityId = 3,
                            Description = "A 15th-century defensive fortress built on the exact site of the ancient Lighthouse of Alexandria, one of the Seven Wonders of the Ancient World.",
                            DestinationName = "Qaitbay Citadel",
                            ImageUrl = "~/images/Alex/CitadelofQaitbay.jpg"
                        },
                        new
                        {
                            DestinationId = 17,
                            CityId = 3,
                            Description = "Sprawling royal gardens along the Mediterranean coast featuring beautiful landscapes, beaches, and the former summer residence of Egyptian royalty.",
                            DestinationName = "Montaza Palace Gardens",
                            ImageUrl = "~/images/Alex/MontazaPalacegarden.jpg"
                        },
                        new
                        {
                            DestinationId = 18,
                            CityId = 3,
                            Description = "A museum housed in an Italian-style palace, displaying artifacts from Alexandria's Pharaonic, Roman, Coptic, and Islamic periods.",
                            DestinationName = "Alexandria National Museum",
                            ImageUrl = "~/images/Alex/AlexandriaNationalMuseum.jpg"
                        },
                        new
                        {
                            DestinationId = 19,
                            CityId = 3,
                            Description = "A massive 27-meter red granite column erected in 297 AD, the largest ancient monument in Alexandria and a remnant of the Serapeum temple.",
                            DestinationName = "Pompey's Pillar",
                            ImageUrl = "~/images/Alex/PompeysPillar.jpg"
                        },
                        new
                        {
                            DestinationId = 20,
                            CityId = 3,
                            Description = "A modern landmark bridge along Alexandria's Corniche, beautifully illuminated at night and offering spectacular Mediterranean Sea views.",
                            DestinationName = "Stanley Bridge",
                            ImageUrl = "~/images/Alex/StanleybridgeinAlexandria.jpg"
                        },
                        new
                        {
                            DestinationId = 21,
                            CityId = 3,
                            Description = "A historical archaeological site featuring a complex of tombs blending Roman, Greek, and Egyptian cultural elements, dating from the 2nd century AD.",
                            DestinationName = "Catacombs of Kom el Shoqafa",
                            ImageUrl = "~/images/Alex/CornicheAlexandria.jpg"
                        },
                        new
                        {
                            DestinationId = 22,
                            CityId = 3,
                            Description = "A well-preserved Roman theater discovered in 1960, featuring marble seating, mosaic floors, and remains of ancient baths and villas.",
                            DestinationName = "Roman Amphitheatre",
                            ImageUrl = "~/images/Alex/CornicheAlexandria.jpg"
                        },
                        new
                        {
                            DestinationId = 23,
                            CityId = 4,
                            Description = "The largest ancient religious complex ever built, covering over 200 acres with massive columns, obelisks, and the famous Great Hypostyle Hall.",
                            DestinationName = "Karnak Temple",
                            ImageUrl = "~/images/Luxuor/Karnak.jpg"
                        },
                        new
                        {
                            DestinationId = 24,
                            CityId = 4,
                            Description = "A magnificent temple complex built around 1400 BC, beautifully illuminated at night and connected to Karnak by the ancient Avenue of Sphinxes.",
                            DestinationName = "Luxor Temple",
                            ImageUrl = "~/images/Luxuor/Louxordromospylône.jpeg"
                        },
                        new
                        {
                            DestinationId = 25,
                            CityId = 4,
                            Description = "An ancient necropolis containing 63 tombs of pharaohs including Tutankhamun, adorned with intricate hieroglyphics and colorful wall paintings.",
                            DestinationName = "Valley of the Kings",
                            ImageUrl = "~/images/Luxuor/LuxorTalderKönige.jpg"
                        },
                        new
                        {
                            DestinationId = 26,
                            CityId = 4,
                            Description = "A stunning mortuary temple built for Egypt's most successful female pharaoh, featuring three terraced levels carved into limestone cliffs.",
                            DestinationName = "Hatshepsut Temple",
                            ImageUrl = "~/images/Luxuor/TemploHatshepsut.jpg"
                        },
                        new
                        {
                            DestinationId = 27,
                            CityId = 4,
                            Description = "Two massive stone statues of Pharaoh Amenhotep III, standing 18 meters tall and guarding the entrance to his mortuary temple for 3,400 years.",
                            DestinationName = "Colossi of Memnon",
                            ImageUrl = "~/images/Luxuor/Hotairballooning.jpg"
                        },
                        new
                        {
                            DestinationId = 28,
                            CityId = 4,
                            Description = "A world-class museum displaying carefully curated artifacts from Thebes and the surrounding area, including royal mummies and exquisite statuary.",
                            DestinationName = "Luxor Museum",
                            ImageUrl = "~/images/Luxuor/LuxorMuseum.jpg"
                        },
                        new
                        {
                            DestinationId = 29,
                            CityId = 4,
                            Description = "An ancient burial site for queens and royal children, featuring beautifully decorated tombs including the famous tomb of Queen Nefertari.",
                            DestinationName = "Valley of the Queens",
                            ImageUrl = "~/images/Luxuor/NileinLuxor.jpg"
                        },
                        new
                        {
                            DestinationId = 30,
                            CityId = 4,
                            Description = "The mortuary temple of Ramses III, one of the best-preserved temples in Egypt with massive walls covered in detailed battle scenes and hieroglyphics.",
                            DestinationName = "Medinet Habu",
                            ImageUrl = "~/images/Luxuor/NileinLuxor.jpg"
                        },
                        new
                        {
                            DestinationId = 31,
                            CityId = 5,
                            Description = "An enchanting temple complex dedicated to the goddess Isis, relocated to Agilkia Island and beautifully preserved with stunning hieroglyphics and columns.",
                            DestinationName = "Philae Temple",
                            ImageUrl = "~/images/Aswan/PhilaeTemple.jpg"
                        },
                        new
                        {
                            DestinationId = 32,
                            CityId = 5,
                            Description = "A massive engineering marvel completed in 1970, controlling Nile flooding and creating Lake Nasser, one of the world's largest artificial lakes.",
                            DestinationName = "Aswan High Dam",
                            ImageUrl = "~/images/Aswan/AswanHighDamNorth.jpg"
                        },
                        new
                        {
                            DestinationId = 33,
                            CityId = 5,
                            Description = "An award-winning museum showcasing the rich history and culture of Nubia, with artifacts spanning from prehistoric times to the present day.",
                            DestinationName = "Nubian Museum",
                            ImageUrl = "~/images/Aswan/NubianMuseum.jpg"
                        },
                        new
                        {
                            DestinationId = 34,
                            CityId = 5,
                            Description = "A massive obelisk still attached to its bedrock, offering unique insights into ancient Egyptian stone-working techniques and quarrying methods.",
                            DestinationName = "Unfinished Obelisk",
                            ImageUrl = "~/images/Aswan/UnfinishedObeliskinAswan.jpg"
                        },
                        new
                        {
                            DestinationId = 35,
                            CityId = 5,
                            Description = "An ancient island settlement containing Nubian villages, archaeological ruins, and the Aswan Museum, set in the middle of the Nile River.",
                            DestinationName = "Elephantine Island",
                            ImageUrl = "~/images/Aswan/Elephantine.jpeg"
                        },
                        new
                        {
                            DestinationId = 36,
                            CityId = 5,
                            Description = "Two massive rock-cut temples built by Ramses II, featuring four colossal statues at the entrance and relocated to save them from Lake Nasser.",
                            DestinationName = "Abu Simbel Temples",
                            ImageUrl = "~/images/Aswan/TemploRamsésIIAbu_Simbel.jpg"
                        },
                        new
                        {
                            DestinationId = 37,
                            CityId = 5,
                            Description = "Colorful traditional villages where Nubian culture thrives, offering authentic experiences with local crafts, music, cuisine, and warm hospitality.",
                            DestinationName = "Nubian Village",
                            ImageUrl = "~/images/Aswan/NubianVillage.jpg"
                        },
                        new
                        {
                            DestinationId = 38,
                            CityId = 6,
                            Description = "Egypt's first national park featuring pristine coral reefs, diverse marine life, and stunning desert landscapes at the southern tip of the Sinai Peninsula.",
                            DestinationName = "Ras Mohammed National Park",
                            ImageUrl = "~/images/SharmElshiekh/RasMuhammad.jpg"
                        },
                        new
                        {
                            DestinationId = 39,
                            CityId = 6,
                            Description = "A vibrant beachfront promenade lined with restaurants, shops, and hotels, offering crystal-clear waters perfect for swimming and snorkeling.",
                            DestinationName = "Naama Bay",
                            ImageUrl = "~/images/SharmElshiekh/NaamaBay.jpg"
                        },
                        new
                        {
                            DestinationId = 40,
                            CityId = 6,
                            Description = "A modern entertainment complex featuring restaurants, ice skating, fountains, open-air cinema, and nightly cultural shows in a beautifully designed plaza.",
                            DestinationName = "SOHO Square",
                            ImageUrl = "~/images/SharmElshiekh/SOHOSquare.jpg"
                        },
                        new
                        {
                            DestinationId = 41,
                            CityId = 6,
                            Description = "A traditional Egyptian bazaar offering authentic shopping experiences with spices, textiles, souvenirs, and local handicrafts at bargain prices.",
                            DestinationName = "Old Market",
                            ImageUrl = "~/images/SharmElshiekh/SharmElSheikhOldMarket.jpg"
                        },
                        new
                        {
                            DestinationId = 42,
                            CityId = 6,
                            Description = "A tranquil beach area known for its excellent diving and snorkeling spots, with easy access to beautiful coral reefs and marine life.",
                            DestinationName = "Shark's Bay",
                            ImageUrl = "~/images/SharmElshiekh/SharksBay.jpeg"
                        },
                        new
                        {
                            DestinationId = 43,
                            CityId = 6,
                            Description = "A breathtaking island famous for its crystal-clear waters, rich coral reefs, and vibrant marine life—one of Sharm El Sheikh’s top snorkeling and diving destinations.",
                            DestinationName = "Tiran Island",
                            ImageUrl = "~/images/SharmElshiekh/TiranIsland.jpg"
                        },
                        new
                        {
                            DestinationId = 44,
                            CityId = 7,
                            Description = "A protected marine reserve with pristine white sandy beaches, crystal-clear turquoise waters, and some of the Red Sea's best snorkeling spots.",
                            DestinationName = "Giftun Island",
                            ImageUrl = "~/images/Hurghada/Giftunisland.jpg"
                        },
                        new
                        {
                            DestinationId = 45,
                            CityId = 7,
                            Description = "A modern waterfront development featuring luxury yachts, upscale restaurants, boutique shops, and vibrant nightlife along scenic boardwalks.",
                            DestinationName = "Hurghada Marina",
                            ImageUrl = "~/images/Hurghada/HurghadaMarina.jpg"
                        },
                        new
                        {
                            DestinationId = 46,
                            CityId = 7,
                            Description = "The historic heart of Hurghada with traditional Egyptian markets, authentic local eateries, and a glimpse into the city's fishing village origins.",
                            DestinationName = "El Dahar Old Town",
                            ImageUrl = "~/images/Hurghada/SahlHasheesh.jpg"
                        },
                        new
                        {
                            DestinationId = 47,
                            CityId = 7,
                            Description = "An impressive open-air museum featuring over 40 intricate sand sculptures depicting historical figures, mythology, and Egyptian landmarks.",
                            DestinationName = "Sand City Hurghada",
                            ImageUrl = "~/images/Hurghada/ElGouna.jpg"
                        },
                        new
                        {
                            DestinationId = 48,
                            CityId = 7,
                            Description = "A state-of-the-art aquarium showcasing Red Sea marine life, rainforest exhibits, and interactive experiences with diverse aquatic species.",
                            DestinationName = "Hurghada Grand Aquarium",
                            ImageUrl = "~/images/Hurghada/Grand Aquarium.jpg"
                        },
                        new
                        {
                            DestinationId = 49,
                            CityId = 7,
                            Description = "One of Africa's largest water parks featuring thrilling slides, wave pools, lazy rivers, and family-friendly attractions spread across 50 attractions.",
                            DestinationName = "Makadi Water World",
                            ImageUrl = "~/images/Hurghada/MakadiBay.jpg"
                        },
                        new
                        {
                            DestinationId = 50,
                            CityId = 8,
                            Description = "Egypt's only natural waterfalls, created when two artificial lakes were connected, surrounded by stunning desert landscapes and diverse wildlife.",
                            DestinationName = "Wadi El Rayan Waterfalls",
                            ImageUrl = "~/images/Fayoum/WaterfallsofWadiElRayan.jpg"
                        },
                        new
                        {
                            DestinationId = 51,
                            CityId = 8,
                            Description = "A UNESCO World Heritage Site known as Valley of the Whales, containing fossils of ancient whales that demonstrate their evolution from land mammals.",
                            DestinationName = "Wadi El Hitan",
                            ImageUrl = "~/images/Fayoum/DimihElseba.jpg"
                        },
                        new
                        {
                            DestinationId = 52,
                            CityId = 8,
                            Description = "Egypt's third-largest lake and oldest natural lake, offering birdwatching opportunities, fishing, and scenic desert views dating back 70 million years.",
                            DestinationName = "Qarun Lake",
                            ImageUrl = "~/images/Fayoum/QarunLake.jpg"
                        },
                        new
                        {
                            DestinationId = 53,
                            CityId = 8,
                            Description = "A charming artistic village known for pottery workshops, galleries, eco-lodges, and stunning views of Lake Qarun and surrounding landscapes.",
                            DestinationName = "Tunis Village",
                            ImageUrl = "~/images/Fayoum/TunisVillage.jpg"
                        },
                        new
                        {
                            DestinationId = 54,
                            CityId = 8,
                            Description = "An archaeological museum displaying artifacts from ancient Fayoum, including Greco-Roman period findings and the famous Fayoum portraits.",
                            DestinationName = "Kom Oshim Museum",
                            ImageUrl = "~/images/Fayoum/HawaraPyramid.jpeg"
                        },
                        new
                        {
                            DestinationId = 55,
                            CityId = 8,
                            Description = "A well-preserved Middle Kingdom temple dedicated to the serpent goddess Renenutet, featuring intact stone structures and ancient reliefs.",
                            DestinationName = "Madinet Madi Temple",
                            ImageUrl = "~/images/Fayoum/MagicLake.jpg"
                        },
                        new
                        {
                            DestinationId = 56,
                            CityId = 9,
                            Description = "A sacred mountain where Moses is believed to have received the Ten Commandments, offering spectacular sunrise views and spiritual significance to three major religions.",
                            DestinationName = "Mount Sinai",
                            ImageUrl = "~/images/Sinai/sinaiMount.jpeg"
                        },
                        new
                        {
                            DestinationId = 57,
                            CityId = 9,
                            Description = "The world's oldest continuously functioning Christian monastery, built in the 6th century and housing priceless icons, manuscripts, and the alleged burning bush.",
                            DestinationName = "Saint Catherine's Monastery",
                            ImageUrl = "~/images/Sinai/Katharinenkloster.jpg"
                        },
                        new
                        {
                            DestinationId = 58,
                            CityId = 9,
                            Description = "A stunning natural wonder featuring narrow passages between towering walls of multicolored sandstone in shades of red, yellow, purple, and gold.",
                            DestinationName = "Colored Canyon",
                            ImageUrl = "~/images/Sinai/AbuGalumProtectorate.jpg"
                        },
                        new
                        {
                            DestinationId = 59,
                            CityId = 9,
                            Description = "A world-famous diving site consisting of a 130-meter deep submarine sinkhole with crystal-clear waters and vibrant coral formations.",
                            DestinationName = "Blue Hole Dahab",
                            ImageUrl = "~/images/Sinai/theBlueHole.jpg"
                        },
                        new
                        {
                            DestinationId = 60,
                            CityId = 9,
                            Description = "A protected area of pristine beaches, coral reefs, and rugged mountains, accessible only by camel or foot, offering untouched natural beauty.",
                            DestinationName = "Abu Galum Reserve",
                            ImageUrl = "~/images/Sinai/AbuGalumProtectorate.jpg"
                        },
                        new
                        {
                            DestinationId = 61,
                            CityId = 9,
                            Description = "A historic Ottoman fortress overlooking the Gulf of Aqaba, offering insights into the region's strategic military history and coastal defense systems.",
                            DestinationName = "Nuweiba Castle",
                            ImageUrl = "~/images/Sinai/Nuweiba.jpg"
                        },
                        new
                        {
                            DestinationId = 62,
                            CityId = 10,
                            Description = "A sheltered bay famous for swimming with sea turtles and dugongs in crystal-clear shallow waters, ideal for snorkeling and underwater photography.",
                            DestinationName = "Abu Dabbab Bay",
                            ImageUrl = "~/images/MarsaAlam/Abu_Dabbab.jpg"
                        },
                        new
                        {
                            DestinationId = 63,
                            CityId = 10,
                            Description = "A horseshoe-shaped reef known for resident pods of spinner dolphins, offering unforgettable opportunities to swim alongside these playful marine mammals.",
                            DestinationName = "Sataya Dolphin Reef",
                            ImageUrl = "~/images/MarsaAlam/Sataya Dolphin Reef.jpg"
                        },
                        new
                        {
                            DestinationId = 64,
                            CityId = 10,
                            Description = "One of the northernmost mangrove forests on Earth, featuring unique ecosystems with diverse birdlife and marine species in protected coastal waters.",
                            DestinationName = "El Qulan Mangrove Forest",
                            ImageUrl = "~/images/MarsaAlam/Qulan.jpg"
                        },
                        new
                        {
                            DestinationId = 65,
                            CityId = 10,
                            Description = "A vast protected area encompassing desert mountains, pristine beaches, coral reefs, and Bedouin heritage sites along 60 kilometers of coastline.",
                            DestinationName = "Wadi El Gemal National Park",
                            ImageUrl = "~/images/MarsaAlam/Wadi_el_Gemal.jpg"
                        },
                        new
                        {
                            DestinationId = 66,
                            CityId = 10,
                            Description = "A luxurious resort marina offering waterfront dining, shopping, yacht charters, and diving excursions in an elegant Mediterranean-style setting.",
                            DestinationName = "Port Ghalib Marina",
                            ImageUrl = "~/images/MarsaAlam/PortGhalibMarina.jpg"
                        },
                        new
                        {
                            DestinationId = 67,
                            CityId = 10,
                            Description = "A protected horseshoe-shaped reef sanctuary where spinner dolphins rest during the day, offering regulated swimming encounters with these graceful creatures.",
                            DestinationName = "Samadai Dolphin House",
                            ImageUrl = "~/images/MarsaAlam/samadi.jpg"
                        },
                        new
                        {
                            DestinationId = 68,
                            CityId = 11,
                            Description = "A stunning beach surrounded by natural rock formations creating a protected swimming cove, where Cleopatra allegedly bathed during her visits.",
                            DestinationName = "Cleopatra Beach",
                            ImageUrl = "~/images/Matrouh/Cleopatra.jpg"
                        },
                        new
                        {
                            DestinationId = 69,
                            CityId = 11,
                            Description = "A scenic coastal promenade stretching along pristine Mediterranean beaches with turquoise waters, cafes, and stunning sunset views.",
                            DestinationName = "Marsa Matrouh Corniche",
                            ImageUrl = "~/images/Matrouh/Marsa Matrouh Corniche.jpg"
                        },
                        new
                        {
                            DestinationId = 70,
                            CityId = 11,
                            Description = "A beautiful white sand beach with crystal-clear shallow waters, perfect for families and swimmers seeking a peaceful Mediterranean coastal experience.",
                            DestinationName = "Al Aghla Beach",
                            ImageUrl = "~/images/Matrouh/Algbla beach.jpg"
                        },
                        new
                        {
                            DestinationId = 71,
                            CityId = 11,
                            Description = "A museum documenting the North African Campaign of World War II, featuring military artifacts, weapons, and exhibits about the desert battles.",
                            DestinationName = "Matrouh War Museum",
                            ImageUrl = "~/images/Matrouh/warmuseum.webp"
                        },
                        new
                        {
                            DestinationId = 72,
                            CityId = 11,
                            Description = "Located in a cave used as Field Marshal Rommel's headquarters during WWII, displaying military equipment and information about the Desert Fox's campaigns.",
                            DestinationName = "Rommel Museum",
                            ImageUrl = "~/images/Matrouh/Rommel.jpg"
                        });
                });

            modelBuilder.Entity("EgyptExploring.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("TripDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TripPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TripId");

                    b.HasIndex("CityId");

                    b.ToTable("Trips", (string)null);

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            CityId = 1,
                            TripDescription = "Explore the ancient wonders of Cairo including the Egyptian Museum, Cairo Tower, and Khan El Khalili bazaar.",
                            TripName = "Cairo Historical Adventure",
                            TripPrice = 2500m
                        },
                        new
                        {
                            TripId = 2,
                            CityId = 2,
                            TripDescription = "Visit the iconic Pyramids of Giza, Great Sphinx, and Saqqara Step Pyramid.",
                            TripName = "Giza Pyramids & Sphinx",
                            TripPrice = 1800m
                        },
                        new
                        {
                            TripId = 3,
                            CityId = 3,
                            TripDescription = "Discover Alexandria's Greco-Roman history including Bibliotheca Alexandrina, Qaitbay Citadel, and Pompey's Pillar.",
                            TripName = "Alexandria Heritage Tour",
                            TripPrice = 2300m
                        },
                        new
                        {
                            TripId = 4,
                            CityId = 4,
                            TripDescription = "A cultural journey through Luxor’s famous temples and the Valley of the Kings.",
                            TripName = "Luxor Temple Discovery",
                            TripPrice = 3200m
                        },
                        new
                        {
                            TripId = 5,
                            CityId = 5,
                            TripDescription = "Enjoy a luxury cruise along the Nile from Aswan to Kom Ombo, visiting Philae Temple and High Dam.",
                            TripName = "Aswan Nile Cruise",
                            TripPrice = 4000m
                        },
                        new
                        {
                            TripId = 6,
                            CityId = 6,
                            TripDescription = "Experience world-class diving and snorkeling in the Red Sea with a relaxing resort stay.",
                            TripName = "Sharm El-Sheikh Diving Tour",
                            TripPrice = 3500m
                        },
                        new
                        {
                            TripId = 7,
                            CityId = 7,
                            TripDescription = "Relax on the stunning beaches of Hurghada with optional water sports and desert safari.",
                            TripName = "Hurghada Beach Escape",
                            TripPrice = 2800m
                        },
                        new
                        {
                            TripId = 8,
                            CityId = 8,
                            TripDescription = "A relaxing eco-trip exploring Wadi El Rayan waterfalls and Qarun Lake.",
                            TripName = "Fayoum Nature Escape",
                            TripPrice = 2000m
                        },
                        new
                        {
                            TripId = 9,
                            CityId = 9,
                            TripDescription = "Explore Mount Sinai, Saint Catherine’s Monastery, and the beautiful Colored Canyon.",
                            TripName = "Sinai Adventure Package",
                            TripPrice = 3700m
                        },
                        new
                        {
                            TripId = 10,
                            CityId = 10,
                            TripDescription = "Dive into the crystal-clear waters of Marsa Alam to explore colorful marine life and visit Wadi El Gemal National Park.",
                            TripName = "Marsa Alam Coral Reefs Tour",
                            TripPrice = 4600m
                        },
                        new
                        {
                            TripId = 11,
                            CityId = 11,
                            TripDescription = "Relax on the stunning white sandy beaches of Cleopatra Beach and Al Aghla, explore the historic Rommel Museum, and enjoy the beautiful turquoise waters along Marsa Matrouh Corniche.",
                            TripName = "Matrouh Mediterranean Escape",
                            TripPrice = 3800m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EgyptExploring.Models.Booking", b =>
                {
                    b.HasOne("EgyptExploring.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptExploring.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EgyptExploring.Models.Destination", b =>
                {
                    b.HasOne("EgyptExploring.Models.City", "City")
                        .WithMany("Destinations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EgyptExploring.Models.Trip", b =>
                {
                    b.HasOne("EgyptExploring.Models.City", "City")
                        .WithMany("Trips")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EgyptExploring.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EgyptExploring.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EgyptExploring.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EgyptExploring.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EgyptExploring.Models.City", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
